<?php

return array (
  'categories' => 
  array (
    0 => 
    array (
      'id' => '4',
      'name' => 'Decorative Finishes',
      'order' => ' 0',
      'created_at' => '2024-11-05 14:47:10',
      'updated_at' => '2024-11-05 14:47:10',
    ),
    1 => 
    array (
      'id' => '5',
      'name' => 'FRP Panels & Hygienic Solutions',
      'order' => ' 0',
      'created_at' => '2024-11-05 14:47:16',
      'updated_at' => '2024-11-05 14:47:16',
    ),
    2 => 
    array (
      'id' => '6',
      'name' => 'Flooring',
      'order' => ' 0',
      'created_at' => '2024-11-05 14:47:21',
      'updated_at' => '2024-11-05 14:47:21',
    ),
    3 => 
    array (
      'id' => '8',
      'name' => 'Acoustic Plaster',
      'order' => ' 0',
      'created_at' => '2024-11-05 14:47:39',
      'updated_at' => '2024-11-05 14:47:39',
    ),
    4 => 
    array (
      'id' => '9',
      'name' => 'Wall Clading',
      'order' => ' 0',
      'created_at' => '2025-01-17 08:20:05',
      'updated_at' => '2025-01-17 08:20:05',
    ),
  ),
  'product_categories' => 
  array (
    0 => 
    array (
      'id' => '3',
      'name' => 'Decorative Finishes',
      'slug' => 'finishes',
      'created_at' => '2024-11-05 14:48:31',
      'updated_at' => '2024-11-05 14:48:31',
    ),
    1 => 
    array (
      'id' => '4',
      'name' => 'FRP',
      'slug' => 'frp',
      'created_at' => '2024-11-05 14:48:38',
      'updated_at' => '2024-11-05 14:48:38',
    ),
    2 => 
    array (
      'id' => '5',
      'name' => 'Decorative Seamless flooring products',
      'slug' => 'decorative-seamless-flooring-products',
      'created_at' => '2024-11-05 14:48:46',
      'updated_at' => '2026-01-30 09:39:46',
    ),
    3 => 
    array (
      'id' => '6',
      'name' => 'Wall Clading',
      'slug' => 'wallclading',
      'created_at' => '2024-11-05 14:48:59',
      'updated_at' => '2024-11-05 14:48:59',
    ),
    4 => 
    array (
      'id' => '7',
      'name' => 'Acoustic solutions, seamless acoustic panels and noise reduction floorings.',
      'slug' => 'acoustic-plaster',
      'created_at' => '2024-11-05 14:49:11',
      'updated_at' => '2026-01-30 09:41:21',
    ),
  ),
  'blogs' => 
  array (
    0 => 
    array (
      'id' => '19',
      'title' => 'Flooring',
      'slug' => 'flooring',
      'content' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\\\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
      'image' => 'blog_images/DwgmdSzJIphXcoPXI2Mazd2W4sMSKd0UMTXuC9qX.png',
      'project_images' => '[\\"blog_images\\\\/ZxDc2Oy7WFtrU9CD9D6ZmkA3DPH9y6SMNojmXlzU.png\\",\\"blog_images\\\\/ROFhkFJqLjUJGY0Ln34iOVi0iBFNdCmKfHBzx7x4.png\\",\\"blog_images\\\\/sCg8GPO120FqL6EituvwzMOEAwbL4FqotSR4MSNT.png\\",\\"blog_images\\\\/JzruRZEqBnFJVgiP1e2HFzhiQ0RXMA2T5qTFQhkP.png\\"]',
      'author' => 'Globe Coat',
      'category_id' => ' NULL',
      'status' => 'Published',
      'created_at' => '2025-03-13 13:42:46',
      'updated_at' => '2025-03-13 13:42:46',
    ),
  ),
  'blog_category' => 
  array (
    0 => 
    array (
      'id' => '18',
      'blog_id' => ' 19',
      'category_id' => ' 6',
    ),
  ),
  'news' => 
  array (
    0 => 
    array (
      'id' => '3',
      'category_id' => ' NULL',
      'title' => '1.Flooring Finishes: Finding the Right Balance of Beauty and Function',
      'slug' => 'floorings',
      'content' => 'When selecting flooring finishes for your interior design, it\\\'s important to find a balance between beauty and practicality. The right flooring not only enhances the aesthetic appeal of a room but also contributes to the overall comfort and functionality of your living space.\\r\\nHardwood floors are a classic option, offering warmth, elegance, and timeless beauty. Available in a wide range of stains and finishes, hardwood floors can be tailored to fit any interior style, from rustic and weathered to sleek and contemporary. The natural grains of wood bring texture and depth to any space, making them ideal for living rooms, bedrooms, and hallways.\\r\\nFor those seeking a more budget-friendly yet stylish option, luxury vinyl plank (LVP) and laminate floors are excellent choices. These materials mimic the appearance of wood, stone, or tile at a fraction of the price. LVP is particularly known for its durability and water resistance.\\r\\nTile floors, whether ceramic, porcelain, or natural stone, offer excellent durability and come in a variety of patterns and finishes. \\r\\nWhether you opt for the timeless charm of hardwood or the modern versatility of tiles, choosing the right flooring finish is crucial for creating a cohesive, functional, and visually stunning interior.',
      'author' => 'Globe Coat',
      'status' => 'published',
      'thumbnail_image' => ' NULL',
      'project_images' => '\\"[]\\"',
      'created_at' => '2024-11-15 13:21:59',
      'updated_at' => '2024-11-15 13:21:59',
    ),
    1 => 
    array (
      'id' => '4',
      'category_id' => ' NULL',
      'title' => '2.Finishes as the Foundation of Interior Style',
      'slug' => 'finish-as',
      'content' => 'When designing a home or commercial space, many people focus primarily on layout, color schemes, and furniture placement. However, one of the most crucial elements in defining the overall aesthetic and ambiance of a room is often overlooked: finishes. The term \\"finishes\\" refers to the materials and treatments applied to surfaces, such as walls, floors, ceilings, and furniture. These are the final touches that not only add visual appeal but also influence the texture, durability, and overall feel of a space.\\r\\nThe Role of Finishes in Interior Design\\r\\nFinishes provide the foundation for an interior style by setting the tone for the entire room. Whether sleek and modern, rustic and organic, or luxurious and refined, the choices made in finishes can enhance or detract from the intended atmosphere. For example, a polished marble countertop exudes sophistication, while reclaimed wood flooring brings warmth and earthiness to a space.\\r\\nTypes of Finishes and Their Impact\\r\\nWood Finishes: Whether it\\\'s a smooth lacquered surface or a weathered, matte texture, wood finishes contribute to the character of a room. High-gloss varnish gives furniture a contemporary, high-end look, while matte or distressed finishes can create a more rustic or industrial vibe.\\r\\nMetal Finishes: Brass, copper, matte black, and polished chrome—metal finishes are integral in both contemporary and vintage-inspired interiors. Polished metals can add shine and luxury, while matte finishes can bring a subtler, more modern touch.\\r\\nPaint and Wall Treatments: The finish of a wall paint can drastically alter a room\\\'s energy. Glossy or satin paints reflect more light, making spaces feel brighter and more expansive. In contrast, matte or eggshell finishes absorb light, offering a softer, cozier ambiance.\\r\\nTextiles: Upholstery fabrics, curtains, and cushions also contribute to a room’s finish. Velvet, linen, and leather all bring different textures and depths to the design, balancing both comfort and style.\\r\\nFinishes as a Reflection of Personal Style\\r\\nUltimately, finishes are the vehicle through which a homeowner or designer expresses personal taste and style. A consistent approach to finishes helps establish a cohesive narrative within a space. By thoughtfully selecting and combining different materials, textures, and treatments, finishes become the backbone of an interior\\\'s personality, creating a room that feels both functional and beautiful.\\r\\nIn interior design, finishes are more than just surface-level details—they are the unsung heroes that define a space’s visual language. They transform bare walls and floors into a seamless, harmonious environment that supports the broader design vision.',
      'author' => 'Globe Coat',
      'status' => 'published',
      'thumbnail_image' => ' NULL',
      'project_images' => '\\"[]\\"',
      'created_at' => '2024-11-15 13:22:31',
      'updated_at' => '2024-11-15 13:22:31',
    ),
    2 => 
    array (
      'id' => '5',
      'category_id' => ' NULL',
      'title' => 'test',
      'slug' => 'testasdf',
      'content' => 'test',
      'author' => 'Globe Coat',
      'status' => 'published',
      'thumbnail_image' => 'news_images/Em5gupDEg6HncyOMWNBoRxUCvO4mmgHs9LLxqjJe.png',
      'project_images' => '\\"[\\\\\\"news_images\\\\\\\\\\\\/C4OetgEVdoVvZ6ehrqGZuaB2O0SNrgVay8WyTpHt.jpg\\\\\\"]\\"',
      'created_at' => '2025-03-13 10:50:32',
      'updated_at' => '2025-03-13 10:50:32',
    ),
    3 => 
    array (
      'id' => '6',
      'category_id' => ' NULL',
      'title' => 'test',
      'slug' => 'test',
      'content' => 'test',
      'author' => 'test',
      'status' => 'published',
      'thumbnail_image' => 'news_images/3HFdRdn4n64X3mch4qq1kAOzIofaHsXM923D6WRy.png',
      'project_images' => '\\"[\\\\\\"news_images\\\\\\\\\\\\/RpgKlExQ1iMZOlHAqQN9W118oqASIEnYz5pLgBAH.png\\\\\\"]\\"',
      'created_at' => '2025-04-14 07:43:07',
      'updated_at' => '2025-04-14 07:43:07',
    ),
  ),
  'products' => 
  array (
    0 => 
    array (
      'id' => '33',
      'category_id' => ' 4',
      'title' => 'LAMILUX Embossed',
      'slug' => 'lamilux-embossed',
      'description' => '<p>The LAMILUX Embossed product range features a textured and glossy surface. The glass-fibre-reinforced polyester laminate comes with a balanced glass content as well as an optional UV and weather-resistant film or gelcoat layer. Challenges posed by curved structures can be easily overcome thanks to the flexible resin system. The product is suitable for a wide range of indoor and outdoor applications.</p>',
      'thumbnail_image' => 'products/thumbnails/0tinWjBcDJE2qzxQYEjcwMnKTB7rXKb0HRITwidA.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/13YCgPvrffb8azksIl5B4Dp7R9z8z6eLCDavvS5N.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:46:36',
      'updated_at' => '2025-04-08 12:46:36',
    ),
    1 => 
    array (
      'id' => '34',
      'category_id' => ' 4',
      'title' => 'LAMILUX woven roving',
      'slug' => 'lamilux-woven-roving',
      'description' => '<p>The LAMILUX Woven Roving range consists of glass-fibre-reinforced polyester laminates with a balanced glass content. The surface can also be sealed with a gelcoat layer on request for even better UV and weather resistance and a less prominent imprint of the woven roving structure. The reinforced fabric increases the mechanical strength of the product and results in lower linear expansion coefficients.</p>',
      'thumbnail_image' => 'products/thumbnails/tvm9gNkeM8lZuZNgIJxPudU9UiyNzPk0DYa5GWNV.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/SaufVNUYRwB7mDzzWb1qLM7AfG8WcXpkFMrOydLW.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:49:12',
      'updated_at' => '2025-04-08 12:49:12',
    ),
    2 => 
    array (
      'id' => '35',
      'category_id' => ' 4',
      'title' => 'LAMILUX HG 4000',
      'slug' => 'lamilux-hg-4000',
      'description' => '<p>Our premium quality LAMILUX HG 4000 combines the advantages of fibre-glass-reinforced composites with the appearance of aluminium. This quality also offers a smooth, high-gloss surface for exacting requirements regarding visual appearance. The surface is sealed with a gelcoat layer, providing even better resistance to ultra-violet light and weathering.</p>',
      'thumbnail_image' => 'products/thumbnails/lIJ4W3XHMfA8DCc00BtSVjyxb3eX3IyaPs6groaJ.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/ZHmj1snS5dD8tfWdqqfjmNdHqSEL1t33TbfGwzWA.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:49:48',
      'updated_at' => '2025-04-08 12:49:48',
    ),
    3 => 
    array (
      'id' => '36',
      'category_id' => ' 4',
      'title' => 'LAMILUX Super',
      'slug' => 'lamilux-super',
      'description' => '<p>The LAMILUX Super range consists of glass-fibre-reinforced polyester laminates with a balanced glass content. This versatile all-round product is suitable for a wide range of indoor and outdoor applications.</p>',
      'thumbnail_image' => 'products/thumbnails/FWz4ASZby01VkpvdkUiZbjMIKmbejDZN9SyPuAbf.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/7KP1BY6O5hMeWIlQlWlXkqB3uAK4FsWVMpk4trRk.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:50:33',
      'updated_at' => '2025-04-08 12:50:33',
    ),
    4 => 
    array (
      'id' => '37',
      'category_id' => ' 4',
      'title' => 'LAMILUX AntiBac',
      'slug' => 'lamilux-antibac',
      'description' => '<p>LAMILUX has developed a new type of composite material for the medical sector: the fibre-reinforced polymer features a special silver nanoparticle surface which produces an anti-bacterial effect. This means that germs on this surface die within a few hours. The innovative material is thus eminently suitable as a wall covering in places such as operating theatres and other medical facilities.<br>Besides use in the medical sector, there are also numerous applications for this hi-tech, anti-bacterial material in the food industry. More precisely, it is used in areas where high hygiene standards must be met and sterility is a top priority, such as processing facilities, slaughter houses, and refrigerated warehouses, storerooms and vehicles.</p>',
      'thumbnail_image' => 'products/thumbnails/ptBcEPTXMMaCGdpDtw26VCgPopqKy2UKLwZXCTds.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/Qz8yK5AftyK1K6MRtdJDS8OAeC3K98ip66mnyzMa.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:51:17',
      'updated_at' => '2025-04-08 12:51:17',
    ),
    5 => 
    array (
      'id' => '38',
      'category_id' => ' 4',
      'title' => 'LAMILUX TextureWall',
      'slug' => 'lamilux-texturewall',
      'description' => '<p>LAMILUX TextureWall is a glassfiber reinforced laminate combining outstanding mechanical properties of composites with an attractive and extremely durable facade plaster surface for the first time.</p>',
      'thumbnail_image' => 'products/thumbnails/44zS478yBnp0OuICLDfUNcaIkH6lozQnJT6ohEOp.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/mAShRxaXR1sbOFfCMtAsk4p33k9BoP6HRMAwr09V.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:52:06',
      'updated_at' => '2025-04-08 12:52:06',
    ),
    6 => 
    array (
      'id' => '39',
      'category_id' => ' 4',
      'title' => 'LAMILUX FireShield®',
      'slug' => 'lamilux-fireshield',
      'description' => '<p>The LAMILUX FireShield® product family includes solutions for a wide range of flame retardant requirements in construction as well as for transport by land, sea and air. Thanks to different reinforcements and different resin systems, LAMILUX FireShield® can be configured to meet flame retardant requirements and a wide range of requirements in terms of mechanics, appearance, hygiene and functionality.</p>',
      'thumbnail_image' => 'products/thumbnails/7czEnhiv8qMUHoZycu6s5ky5hLE7PkG6eRaetXKt.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/zR6JdXsEPaqWKgjiYRzwPo7ftYTdbB5tfmc2KJkP.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:52:43',
      'updated_at' => '2025-04-08 12:52:43',
    ),
    7 => 
    array (
      'id' => '40',
      'category_id' => ' 4',
      'title' => 'LAMILUX X-treme Carbon',
      'slug' => 'lamilux-x-treme-carbon',
      'description' => '<p>With its X-treme Carbon range, LAMILUX is pushing the boundaries of technology and is tapping the full performance potential of fibre-reinforced composites. The strength and rigidity values are many times higher than those of normal composites. This reduces the amount of materials required, resulting in a significant reduction in weight.</p><p>This is made possible through a combination of high-strength, rigid, lightweight carbon fibres with an extremely resilient epoxy resin matrix system.</p>',
      'thumbnail_image' => 'products/thumbnails/tPlgQ1S2TIJoFLIV0synAq6nZyZCi06h06Rlv7Qw.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/L8ejAkzK3MAX2OCZDuwh9MgLyYhfpRDEoAQZp2ND.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:53:20',
      'updated_at' => '2025-04-08 12:53:20',
    ),
    8 => 
    array (
      'id' => '41',
      'category_id' => ' 4',
      'title' => 'LAMI Graph',
      'slug' => 'lami-graph',
      'description' => '<p>LAMILUX Graph is a polyester-resin-based, glass-fibre-reinforced laminate with a high-grade décor paper on the visible side. This product perfectly combines a wide range of designs with the favourable mechanical properties and resistance of glass-fibre reinforced products.</p>',
      'thumbnail_image' => 'products/thumbnails/1vHtp1eELj78M8LIFMo9mvBjGVn0eNmNgmC1lwQy.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/jXViQluz5eCisb2Os2IAspQOVFWnrtcRWL17RMgN.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:53:52',
      'updated_at' => '2025-04-08 12:53:52',
    ),
    9 => 
    array (
      'id' => '42',
      'category_id' => ' 4',
      'title' => 'LAMILUX Anti Slip',
      'slug' => 'lamilux-anti-slip',
      'description' => '<p>LAMILUX Anti Slip is a glass-fibre-reinforced laminate which combines the excellent mechanical properties and durability of glass-fibre reinforced composites with an effective and wear-resistant anti-slip coating.</p>',
      'thumbnail_image' => 'products/thumbnails/cdqEK8lY2OvMXnlzvNpSps3amPO10D7x8M6Trfxi.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/STJ881XiC4ghVqENfE13OGMUJYLcKG0bwAPwcgfE.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:54:34',
      'updated_at' => '2025-04-08 12:54:34',
    ),
    10 => 
    array (
      'id' => '43',
      'category_id' => ' 4',
      'title' => 'Facade Panel',
      'slug' => 'facade-panel',
      'description' => '<p>Made of glass-fibre-reinforced composite, LAMILUX facade panels provide a visually stunning facade system in an extensive range of colours. The extravagant appearance is combined with creative freedom, high resistance to vandalism and the option for backlighting. The product is perfectly suited for rear-ventilated curtain wall facades which are becoming increasingly popular due to the rise in the number of thermal insulation requirements.</p>',
      'thumbnail_image' => 'products/thumbnails/2I9685CrDtyGXiZx321wcUPboZVmL8zLD6eMM7qC.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/81RQxtEAlwhii07HNc5KhTSvC4lXxgW2lMkxLuzT.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:55:09',
      'updated_at' => '2025-04-08 12:55:09',
    ),
    11 => 
    array (
      'id' => '44',
      'category_id' => ' 4',
      'title' => 'LAMILUX LAMIsport X-treme',
      'slug' => 'lamilux-lamisport-x-treme',
      'description' => '<p>LAMIsport X-treme is an innovative composite designed for use in the construction of winter and summer sports equipment. This lightweight material consists of glass or carbon fibre reinforcements and opens up new possibilities in weight reduction, process efficiency and styling.</p>',
      'thumbnail_image' => 'products/thumbnails/4njTmog2etHwSTEtayvyeUgRtfhkLuVKN5E79KGe.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/odLJjHHdMXVDSLeS1xP6hc9aegzp0KlXuMCC2voK.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:55:39',
      'updated_at' => '2025-04-08 12:55:39',
    ),
    12 => 
    array (
      'id' => '45',
      'category_id' => ' 4',
      'title' => 'LAMILUX High Impact',
      'slug' => 'lamilux-high-impact',
      'description' => '<p>LAMILUX High Impact combines outstanding impact resistance and strength with very low weight and an attractive surface which is easy to clean. The combination of a high reinforcement fibre content and a sophisticated special resin makes LAMILUX High Impact ideal for overcoming the high requirements of modern industrial applications.</p>',
      'thumbnail_image' => 'products/thumbnails/m3HE8q30Dc1kwsppoVg4sqcIIJVD7RcAZw0e3nYF.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/UrFC2YNQN5pIZHODxCxT6aB9OL8Wo5auQrFCii61.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:56:09',
      'updated_at' => '2025-04-08 12:56:09',
    ),
    13 => 
    array (
      'id' => '46',
      'category_id' => ' 4',
      'title' => 'LAMILUX LAMIfoamtex',
      'slug' => 'lamilux-lamifoamtex',
      'description' => '<p>LAMILUX LAMIfoamtex is an innovative composite material made of fibre-reinforced plastic with customisable soft-touch décors. It opens up innumerable creative design possibilities and its three-dimensional structure also has a positive effect on the interior acoustics.</p>',
      'thumbnail_image' => 'products/thumbnails/p07EyrXicRCDTqnGPX3BaNHHRD4q9O4BgG4SQibB.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/w1e1rBNtG7gDQABW2iialRzykwluI2meyN6vIJ9m.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:56:40',
      'updated_at' => '2025-04-08 12:56:40',
    ),
    14 => 
    array (
      'id' => '47',
      'category_id' => ' 4',
      'title' => 'LAMILUX X-treme',
      'slug' => 'lamilux-x-treme',
      'description' => '<p>With its X-TREME range, LAMILUX is pushing the boundaries of technology and is tapping the full performance potential of fibre-reinforced composites. The strength and rigidity values are many times higher than those of normal composites.</p><p>This reduces the amount of materials required, saves excess weight and allows useful functions – such as extreme impact resistance or the lowest possible thermal expansion – to be integrated into the product applications.</p><p>With a maximum reinforced fibre content of more than 50% and the extremely viscoplastic epoxy matrix resin system, LAMILUX X-TREME is the most effective composite material on the market.</p>',
      'thumbnail_image' => 'products/thumbnails/vBETR1OqMaJNa9rtJ1d7hLohA2qiWrYJG3ro2ObT.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/EgMJR4ZbDxXofIIwuSZcOqZsa1Ak45UC8zEsdJ2H.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:57:16',
      'updated_at' => '2025-04-08 12:57:16',
    ),
    15 => 
    array (
      'id' => '48',
      'category_id' => ' 4',
      'title' => 'LAMILUX Composite Floor',
      'slug' => 'lamilux-composite-floor',
      'description' => '<p>LAMILUX Composite Floor is an innovative composite floor covering based on a woven fabric-reinforced composite and custom flooring decor layers. The material-to-material bond between the decor flooring layer and the LAMILUX GRP reinforcement means there is no need for the extra weight of adhesive coatings. This quality combied with ist optimum strength and durability – even in demanding applications – and absence of odour makes LAMILUX Composite Floor ideal for intelligent lightweight construction. Moreover, the integral design enables producers to save on raw materials and streamline the manufacturing process during further processing.&nbsp; LAMILUX Composite Floor is available in two options (PVC flooring or decor surface layer).</p>',
      'thumbnail_image' => 'products/thumbnails/GWynZubYi5V9bu7vbA5fAL3PPizsRgpk2kJG26bC.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/fGNhPIxebH83iZCSdyX9gUFzvpSymWTUJKFsyWaR.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:57:56',
      'updated_at' => '2025-04-08 12:57:56',
    ),
    16 => 
    array (
      'id' => '49',
      'category_id' => ' 4',
      'title' => 'LAMILUX SUNSATION®',
      'slug' => 'lamilux-sunsation',
      'description' => '<p>The world innovation LAMILUX SUNSATION® is the long-awaited revolution in the field of fibre-reinforced composites and redefines the standard for outdoor applications. The 20-fold higher UV stability compared to standard GRP expands the horizon in terms of image, appearance, maintenance and value. Whether for recreational vehicles or trucks, even after many years in the sun, LAMILUX SUNSATION® looks like new and enables maximum value retention.</p>',
      'thumbnail_image' => 'products/thumbnails/sCGNtyiEctHWQM7O3KdcsDo06B82Kqr3nd27tcEL.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/XQJSViUklHJeafSikENdyUiQi236PaietdgoREZs.jpg\\"]',
      'additional_information' => 'null',
      'created_at' => '2025-04-08 12:58:39',
      'updated_at' => '2025-04-08 12:58:39',
    ),
    17 => 
    array (
      'id' => '54',
      'category_id' => ' 6',
      'title' => 'Eco and acoustic cladding',
      'slug' => 'eco-and-acoustic-cladding',
      'description' => '<h3>3D big panel board is made of natural stone powder and modified clay.</h3><p>We have selected the inner (outer) projects’ styles that are very popular among designers in the market, and independently developed and produced rammed earth board, concrete board, line stone board, rust board, ripple board, etc.</p><p>It has visual texture effects such as light weight, flexible, breathable, convenient construction, natural simplicity, etc. It can be perfectly integrated with other materials or create a unique design shape. It is suitable for place and irregular space that need to pursue individuality and artistic modeling characteristic</p>',
      'thumbnail_image' => 'products/thumbnails/SDGDIi2Fv73wAY6zJQWsS6O91nzoj9T1vrxz0x7r.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/318w7DuCpmoUpCQYeYbfwwYddG4kDGYg1FLe7sD3.jpg\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:18:31',
      'updated_at' => '2025-04-10 08:18:31',
    ),
    18 => 
    array (
      'id' => '55',
      'category_id' => ' 6',
      'title' => 'Flexi Stone',
      'slug' => 'flexi-stone',
      'description' => '<h3>The innovative wall covering solutions made of natural stone</h3><p>Flexi Stone is a paper thin real stone veneer. The 100% natural stone surface is enforced from the back with fiberglass for better stability and easy processing.<br>This opens up new, unlimited opportunities on almost all surfaces. Available in different decors, in natural slate and quartzite, elegant silver tones to green, gray and black shades.</p><p>Flexi Stone is also very light: It weighs just 1,5 kg per m², which also significantly reduces transport costs compared to massive stone slabs and also helps to reduce the degradation of natural resources.<br>All chemical components of Flexi Stone are harmless to health and correspond to the highest quality standards.</p><p><strong>Flexible</strong></p><ul><li>Offers architects and designers new possibilities Lightweight</li><li>Approximately 1:5 kg / m2</li><li>Static benefits</li><li>Ecological, beginning with transportation Sustainable</li><li>Conserves resource, thickness only 2,5 – 3 mm (conventional wall covers are typically 1 cm)</li></ul>',
      'thumbnail_image' => 'products/thumbnails/b157Ez11Ps5bAU6ZdZ5rcEtN4jDgWHNx4tGWeZbh.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/E7ro7ena0usXWgyW5AX9uynyqdnUxJl9dIkLvPNZ.jpg\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:19:37',
      'updated_at' => '2025-04-10 08:19:37',
    ),
    19 => 
    array (
      'id' => '56',
      'category_id' => ' 6',
      'title' => 'Decorative Sculptural',
      'slug' => 'decorative-sculptural',
      'description' => '<p>Globe coat Sculptural Panel Systems Offer A Seamless Three Dimensional Wall Covering. They Make A Statement Wherever They Are Used. From Large Scale Commercial Areas To Feature Walls In Residential Properties Globe coat Sculptural Walls Add Depth And Grandeur To Any Space. Each Of The 29 Designs Is Created Using A Combination Of Traditional Hand Sculpting And Computer Aided Design To Ensure Total Accuracy During Installation Whilst Retaining The Essence Of Hand Crafting.</p>',
      'thumbnail_image' => 'products/thumbnails/Njj1Y5AviiAN2T5zIROd5zwABZ4nWB9ugck0hDDf.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/CWa0bTe9PX4D1alBuX4fsmqBjJlCzi4jrZA42Kg3.jpg\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:23:17',
      'updated_at' => '2025-04-10 08:23:17',
    ),
    20 => 
    array (
      'id' => '62',
      'category_id' => ' 3',
      'title' => 'Polished Plaster',
      'slug' => 'polished-plaster',
      'description' => '<p>Polished Plaster, also known as Venetian Plaster or Marmarino is an exquisite decorative finish that adds timeless elegance and luxurious texture to any interior space. With its smooth and glossy appearance, this artisanal technique creates a seamless, marble-like finish that beautifully reflects light and enhances the ambiance of your surroundings. Transform your walls into works of art with Polished Plaster, an exquisite choice for those seeking sophistication and in their design.<br>Textured plasters are a fantastic way to add depth and visual interest to your walls, creating a unique and dynamic look for your space. With their textured surfaces, these plasters can mimic seamless appearance of various materials such as stone, brick, or stucco, giving your walls a distinctive and tactile quality. Whether you desire a rustic, industrial, concrete or contemporary aesthetic, textured plasters offer versatility in design, allowing you to achieve the desired atmosphere and style. Elevate your walls to new heights with the captivating allure of textured plasters and transform your space into a truly remarkable environment.<br>&nbsp;</p>',
      'thumbnail_image' => 'products/thumbnails/117lfTjFTd8z8hsnLMayupotxnaAWeLxFGUaqhNz.png',
      'product_images' => '[\\"products\\\\/images\\\\/jNgN4qK9k89xuCS2cewGHLqlDXiiynCFqyJoWqiA.png\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:45:54',
      'updated_at' => '2025-04-10 08:45:54',
    ),
    21 => 
    array (
      'id' => '63',
      'category_id' => ' 3',
      'title' => 'Clay Finishes and Rammed Earth',
      'slug' => 'clay-finishes-and-rammed-earth',
      'description' => '<p>Clay finishes offer a natural and sustainable way to enhance the beauty of your space. With their organic texture and earthy tones, clay finishes create a warm and inviting atmosphere that connects you with nature. These eco-friendly coatings are not only visually appealing but also promote better indoor air quality by regulating humidity and absorbing toxins. Embrace the timeless charm of clay finishes and bring a touch of natural elegance to your walls.</p>',
      'thumbnail_image' => 'products/thumbnails/xcoX4VLjtItCGm04zkFpikLtMVEluMudkQAO23Lm.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/kCqf35Od3i6SaciiKPFZ7kcI6YGQOPuFxx7sOVbE.jpg\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:46:20',
      'updated_at' => '2025-04-10 08:46:20',
    ),
    22 => 
    array (
      'id' => '64',
      'category_id' => ' 3',
      'title' => 'Decorative Paints',
      'slug' => 'decorative-paints',
      'description' => '<p>Decorative paints bring life and personality to your walls, turning them into a canvas for creativity and self-expression. With a wide range of colors, textures, and finishes to choose from, such as metallic effect, rustic, pearly, matte and glossy these paints allow you to add depth, character, and style to any room. Whether you prefer bold and vibrant hues or subtle and serene tones, decorative paints offer endless possibilities to transform your space into a personalized work of art.</p>',
      'thumbnail_image' => 'products/thumbnails/mI79W0BxHk0mqEGknYh0Rx1ygfqPyhExnorBjuOi.png',
      'product_images' => '[\\"products\\\\/images\\\\/ffsp0npnLqZjVZkkKsHKDYQ4F78A6NPa8AsryLAY.png\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:46:47',
      'updated_at' => '2025-04-10 08:46:47',
    ),
    23 => 
    array (
      'id' => '65',
      'category_id' => ' 3',
      'title' => 'Metallic and Rust Paints',
      'slug' => 'metallic-and-rust-paints',
      'description' => '<p>Metallic paints are a captivating and versatile category of decorative paints used to add a touch of elegance and sophistication to interior walls. These paints contain metallic pigments or flakes that create a shimmering, reflective effect when applied to surfaces. They offer a unique way to enhance the visual appeal of any room, turning ordinary walls into stunning focal points.<br>Rust paints, also known as rusted or oxidized paints, are a fascinating option for interior walls that offer a distinct and rustic charm. These paints are designed to mimic the appearance of natural rust, giving walls a weathered and aged look.<br>&nbsp;</p>',
      'thumbnail_image' => 'products/thumbnails/M40oOlNvdRRFeFrcSePazbjLphvObGnsXyQ4aNiJ.png',
      'product_images' => '[\\"products\\\\/images\\\\/Mz1L91locNIM2Yj71roJZ6Xhqab6yhm1DkKFHUeT.png\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:47:17',
      'updated_at' => '2025-04-10 08:47:17',
    ),
    24 => 
    array (
      'id' => '67',
      'category_id' => ' 5',
      'title' => 'Globefloor R Series',
      'slug' => 'globefloor-r-series',
      'description' => '<p>Designed for high-traffic floor areas that demand durability, the Globefloor R Series offers a stronger finish with a slight texture.<br>This option ensures optimal slip resistance, making it ideal for commercial spaces or areas where safety is a priority. Experience the perfect balance of style and functionality with the Globefloor R Series.<br>&nbsp;</p>',
      'thumbnail_image' => 'products/thumbnails/OHF0xxByNOGYukEQ7CDwvcXbv14WhwbylYMTzwQZ.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/MFwWQuyCZVC81XbKT19cT4NCCDAr8WWWykjwG7vF.jpg\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:50:48',
      'updated_at' => '2025-04-10 08:50:48',
    ),
    25 => 
    array (
      'id' => '68',
      'category_id' => ' 5',
      'title' => 'Globefloor P Series',
      'slug' => 'globefloor-p-series',
      'description' => '<p>Achieve a smooth and minimalistic look with our Globefloor P Series. This option provides a sleek, seamless finish that exudes contemporary elegance.<br>With an infinite color range to choose from, you have the freedom to create a truly customized and captivating aesthetic that perfectly suits your space.<br>&nbsp;</p>',
      'thumbnail_image' => 'products/thumbnails/psUZopHD1GsGf6ie7nu8x71O04FzulQ8e8u91v1W.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/lTfmoA4fPcdk6HQo8d1F0hbUpOmss9n3cIK7pskD.jpg\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:51:47',
      'updated_at' => '2025-04-10 08:51:47',
    ),
    26 => 
    array (
      'id' => '69',
      'category_id' => ' 5',
      'title' => 'Globefloor WP Series',
      'slug' => 'globefloor-wp-series',
      'description' => '<p>For areas exposed to moisture and water, such as showers, bathrooms, and spa areas, the Globefloor WP Series is the ultimate waterproof micro-cement solution. Combining the beauty of micro cement with enhanced water resistance, this series offers both style and functionality, allowing you to create breathtaking spaces without compromising on durability or performance.<br>Whether you’re looking for a sleek and modern finish, a durable and textured surface, or a waterproof solution, Globefloor Micro cement has you covered. Our seamless flooring system provides limitless design possibilities while maintaining the highest standards of quality and craftsmanship. Discover the transformative power of Globefloor Micro cement and elevate your space with a seamless flooring solution that surpasses expectations. Get in touch with us to explore the endless design options and discuss how Globefloor Micro Cement can enhance your project.<br>&nbsp;</p>',
      'thumbnail_image' => 'products/thumbnails/eTZtl9nMGbQs3meLCmeXlIqHCnfB0imx7lwiIzCT.jpg',
      'product_images' => '[\\"products\\\\/images\\\\/2qUylbX2ApqsMGRpOSVrxcqxtc1CJs6wpyfTDso0.jpg\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 08:52:18',
      'updated_at' => '2025-04-10 08:52:18',
    ),
    27 => 
    array (
      'id' => '74',
      'category_id' => ' 7',
      'title' => 'Acoustic Solutions® Plaster System',
      'slug' => 'armourcoat-acoustic-plaster-system',
      'description' => '<p>The Acoustic Solutions® Plaster System Is Designed To Optimise The Acoustics Of Interior Spaces.</p><p>From Restaurants, Theatres, Offices, Classrooms, Hotel Receptions And Private Residences, The Use Of Hard Sound Reflective Surfaces Such As Glass, Wood And Stone Can Cause Excessive Sound Reverberation Which Leads To Unpleasant Noise Levels. The Correct Control Of Sound Will Create A Calmer And More Pleasant Environment.</p><p>The Armourcoat Acoustic® Plaster System Offers A Clean Flat And Smooth Mineral Surface That Can Be Applied Seamlessly Over Large Expanses To Both Flat And Curved Surfaces. It Offers Excellent Sound Absorption – To Class ‘A’ Noise Reduction Coefficient.<br>&nbsp;</p>',
      'thumbnail_image' => 'products/thumbnails/nmfyTe6vEoKQhPKReXQcj3fYfW7GTqHtDElZjcqN.png',
      'product_images' => '[\\"products\\\\/images\\\\/LHEusG4U9wx28DHa8qui25JeXRWe0odujlTv1Oeo.png\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 11:23:37',
      'updated_at' => '2025-04-10 11:23:37',
    ),
    28 => 
    array (
      'id' => '75',
      'category_id' => ' 7',
      'title' => 'The Acoustic Solutions® Plaster System',
      'slug' => 'the-armourcoat-acoustic-plaster-system',
      'description' => '<p>The Acoustic Solutions® Plaster System Is Suitable For Use In Both Commercial And Residential Interior Projects Including Major Transport Hubs, Restaurants, Bars And Nightclubs, Cinemas And Theatres, Shopping Centres And Retail Units, Leisure Facilities Such As Swimming Pools And Gymnasiums, Open Plan Office Environments, Corridors And Walkways, Toilet And Washroom Lobbies, Music Rooms, Open Plan Entrance Halls And Living Spaces.</p>',
      'thumbnail_image' => 'products/thumbnails/oA0jRkllrVcONBbaw31dm8VXBaC6wZBHbqGIDJzr.png',
      'product_images' => '[\\"products\\\\/images\\\\/jsJFjQCUrZCSMYWHLM7suKM3XFvYapmKUqq4QtOI.png\\"]',
      'additional_information' => ' NULL',
      'created_at' => '2025-04-10 11:24:01',
      'updated_at' => '2025-04-10 11:24:01',
    ),
  ),
  'team_members' => 
  array (
    0 => 
    array (
      'id' => '1',
      'first_name' => 'Ideal',
      'last_name' => 'Raci',
      'position' => 'CEO',
      'email' => 'ideal.racii@gmail.com',
      'phone_number' => '123123123',
      'image' => ' NULL',
      'personal_details' => 'asdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdf',
      'business_growth' => ' 50',
      'money_management' => ' 30',
      'business_consulting' => ' 25',
      'team_work' => ' 67',
      'created_at' => '2024-10-21 12:02:24',
      'updated_at' => '2024-10-21 12:02:24',
      'facebook' => ' NULL',
      'twitter' => ' NULL',
      'linkedin' => ' NULL',
      'instagram' => ' NULL',
    ),
    1 => 
    array (
      'id' => '3',
      'first_name' => 'Ideal',
      'last_name' => 'Raci',
      'position' => 'CEO',
      'email' => 'idealr1978@gmail.com',
      'phone_number' => '048113790',
      'image' => ' NULL',
      'personal_details' => ' NULL',
      'business_growth' => ' 3',
      'money_management' => ' 21',
      'business_consulting' => ' 11',
      'team_work' => ' 42',
      'created_at' => '2024-10-21 12:57:08',
      'updated_at' => '2024-10-21 12:57:08',
      'facebook' => ' NULL',
      'twitter' => ' NULL',
      'linkedin' => ' NULL',
      'instagram' => ' NULL',
    ),
    2 => 
    array (
      'id' => '4',
      'first_name' => 'Ideal',
      'last_name' => 'Raci',
      'position' => 'CEO',
      'email' => 'idealr1978@s.com',
      'phone_number' => '048113790',
      'image' => ' NULL',
      'personal_details' => ' NULL',
      'business_growth' => ' 33',
      'money_management' => ' 42',
      'business_consulting' => ' 1',
      'team_work' => ' 3',
      'created_at' => '2024-10-21 13:01:18',
      'updated_at' => '2024-10-21 13:01:18',
      'facebook' => ' NULL',
      'twitter' => ' NULL',
      'linkedin' => ' NULL',
      'instagram' => ' NULL',
    ),
    3 => 
    array (
      'id' => '5',
      'first_name' => 'Ideal',
      'last_name' => 'Raci',
      'position' => 'CEO',
      'email' => 'idealr1978@sa.com',
      'phone_number' => '048113790',
      'image' => ' NULL',
      'personal_details' => ' NULL',
      'business_growth' => ' 32',
      'money_management' => ' 12',
      'business_consulting' => ' 99',
      'team_work' => ' 77',
      'created_at' => '2024-10-21 13:04:00',
      'updated_at' => '2024-10-21 13:04:00',
      'facebook' => 'https://www.facebook.com/johndoe',
      'twitter' => 'https://x.com/johndoe',
      'linkedin' => 'https://www.linkedin.com/johndoe',
      'instagram' => 'https://instagram.com/johndoe',
    ),
    4 => 
    array (
      'id' => '6',
      'first_name' => 'Ideal',
      'last_name' => 'Raci',
      'position' => 'CEO',
      'email' => 'idealr1978@aaa.com',
      'phone_number' => '048113790',
      'image' => ' NULL',
      'personal_details' => 'asdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdfasdfgasdfauishdf',
      'business_growth' => ' 33',
      'money_management' => ' 22',
      'business_consulting' => ' 11',
      'team_work' => ' 99',
      'created_at' => '2024-10-21 13:18:21',
      'updated_at' => '2024-10-21 13:18:21',
      'facebook' => 'https://www.facebook.com/johndoe',
      'twitter' => 'https://x.com/johndoe',
      'linkedin' => 'https://www.linkedin.com/johndoe',
      'instagram' => 'https://instagram.com/johndoe',
    ),
  ),
  'navbars' => 
  array (
    0 => 
    array (
      'id' => '11',
      'label' => 'Home',
      'url' => 'home',
      'is_visible' => ' 1',
      'order' => ' 1',
      'created_at' => '2024-10-16 05:13:28',
      'updated_at' => '2024-10-16 05:13:28',
    ),
    1 => 
    array (
      'id' => '12',
      'label' => 'ideal',
      'url' => 'ideal',
      'is_visible' => ' 1',
      'order' => ' 2',
      'created_at' => '2024-10-16 05:14:01',
      'updated_at' => '2024-10-16 05:14:01',
    ),
    2 => 
    array (
      'id' => '13',
      'label' => 'test',
      'url' => 'tes',
      'is_visible' => ' 1',
      'order' => ' 3',
      'created_at' => '2024-10-16 05:16:05',
      'updated_at' => '2024-10-16 05:16:05',
    ),
    3 => 
    array (
      'id' => '14',
      'label' => 'aa',
      'url' => 'aa',
      'is_visible' => ' 1',
      'order' => ' 5',
      'created_at' => '2024-10-16 05:25:38',
      'updated_at' => '2024-10-16 05:25:38',
    ),
  ),
  'pages' => 
  array (
    0 => 
    array (
      'id' => '21',
      'navbar_id' => ' 12',
      'title' => 'test',
      'slug' => ' NULL',
      'content' => 'test',
      'created_at' => '2024-10-24 10:05:04',
      'updated_at' => '2024-10-24 10:05:04',
      'section_one_title' => ' NULL',
      'section_one_content' => ' NULL',
      'section_two_title' => ' NULL',
      'section_two_content' => ' NULL',
      'how_it_works_title' => ' NULL',
      'how_it_works_content' => ' NULL',
      'section_one_service_1_title' => ' NULL',
      'section_one_service_1_content' => ' NULL',
      'section_one_service_2_title' => ' NULL',
      'section_one_service_2_content' => ' NULL',
      'section_one_service_3_title' => ' NULL',
      'section_one_service_3_content' => ' NULL',
    ),
    1 => 
    array (
      'id' => '22',
      'navbar_id' => ' 12',
      'title' => 'sdfa',
      'slug' => ' NULL',
      'content' => 'asdf',
      'created_at' => '2024-10-24 10:06:13',
      'updated_at' => '2024-10-24 10:06:13',
      'section_one_title' => ' NULL',
      'section_one_content' => ' NULL',
      'section_two_title' => ' NULL',
      'section_two_content' => ' NULL',
      'how_it_works_title' => ' NULL',
      'how_it_works_content' => ' NULL',
      'section_one_service_1_title' => ' NULL',
      'section_one_service_1_content' => ' NULL',
      'section_one_service_2_title' => ' NULL',
      'section_one_service_2_content' => ' NULL',
      'section_one_service_3_title' => ' NULL',
      'section_one_service_3_content' => ' NULL',
    ),
    2 => 
    array (
      'id' => '23',
      'navbar_id' => ' 13',
      'title' => 'asdf',
      'slug' => 'asdf',
      'content' => '',
      'created_at' => '2024-10-24 10:10:35',
      'updated_at' => '2024-10-24 10:10:35',
      'section_one_title' => 'asdf',
      'section_one_content' => 'asdf',
      'section_two_title' => 'asdf',
      'section_two_content' => 'asdf',
      'how_it_works_title' => 'asdf',
      'how_it_works_content' => 'asdf',
      'section_one_service_1_title' => ' NULL',
      'section_one_service_1_content' => ' NULL',
      'section_one_service_2_title' => ' NULL',
      'section_one_service_2_content' => ' NULL',
      'section_one_service_3_title' => ' NULL',
      'section_one_service_3_content' => ' NULL',
    ),
    3 => 
    array (
      'id' => '24',
      'navbar_id' => ' 13',
      'title' => 'test',
      'slug' => 'test',
      'content' => '',
      'created_at' => '2024-10-24 11:41:52',
      'updated_at' => '2024-10-24 11:41:52',
      'section_one_title' => ' NULL',
      'section_one_content' => ' NULL',
      'section_two_title' => ' NULL',
      'section_two_content' => ' NULL',
      'how_it_works_title' => 'test',
      'how_it_works_content' => 'asdf',
      'section_one_service_1_title' => 'test1',
      'section_one_service_1_content' => 'test1',
      'section_one_service_2_title' => 'test2te',
      'section_one_service_2_content' => 'test2',
      'section_one_service_3_title' => 'test3t',
      'section_one_service_3_content' => 'test4',
    ),
    4 => 
    array (
      'id' => '25',
      'navbar_id' => ' 12',
      'title' => 'Early',
      'slug' => 'early',
      'content' => '',
      'created_at' => '2024-10-28 08:02:31',
      'updated_at' => '2024-10-28 08:02:31',
      'section_one_title' => ' NULL',
      'section_one_content' => ' NULL',
      'section_two_title' => ' NULL',
      'section_two_content' => ' NULL',
      'how_it_works_title' => 'Early',
      'how_it_works_content' => 'EarlyEarlyEarlyEarlyEarly',
      'section_one_service_1_title' => 'Early',
      'section_one_service_1_content' => 'EarlyEarlyEarlyEarlyEarlyEarly',
      'section_one_service_2_title' => 'Early',
      'section_one_service_2_content' => 'EarlyEarlyEarlyEarly',
      'section_one_service_3_title' => 'Early',
      'section_one_service_3_content' => 'EarlyEarlyEarlyEarlyEarlyEarlyEarly',
    ),
    5 => 
    array (
      'id' => '26',
      'navbar_id' => ' 13',
      'title' => 'sad',
      'slug' => 'sad',
      'content' => '',
      'created_at' => '2024-10-30 12:08:24',
      'updated_at' => '2024-10-30 12:08:24',
      'section_one_title' => ' NULL',
      'section_one_content' => ' NULL',
      'section_two_title' => ' NULL',
      'section_two_content' => ' NULL',
      'how_it_works_title' => 'asd',
      'how_it_works_content' => 'asd',
      'section_one_service_1_title' => 'asd',
      'section_one_service_1_content' => 'asd',
      'section_one_service_2_title' => 'dasd',
      'section_one_service_2_content' => 'asd',
      'section_one_service_3_title' => 'asd',
      'section_one_service_3_content' => 'asd',
    ),
  ),
);
